\documentclass[]{article}
\usepackage{lmodern}
\usepackage{amssymb,amsmath}
\usepackage{ifxetex,ifluatex}
\usepackage{fixltx2e} % provides \textsubscript
\ifnum 0\ifxetex 1\fi\ifluatex 1\fi=0 % if pdftex
  \usepackage[T1]{fontenc}
  \usepackage[utf8]{inputenc}
\else % if luatex or xelatex
  \ifxetex
    \usepackage{mathspec}
  \else
    \usepackage{fontspec}
  \fi
  \defaultfontfeatures{Ligatures=TeX,Scale=MatchLowercase}
\fi
% use upquote if available, for straight quotes in verbatim environments
\IfFileExists{upquote.sty}{\usepackage{upquote}}{}
% use microtype if available
\IfFileExists{microtype.sty}{%
\usepackage{microtype}
\UseMicrotypeSet[protrusion]{basicmath} % disable protrusion for tt fonts
}{}
\usepackage[margin=1in]{geometry}
\usepackage{hyperref}
\hypersetup{unicode=true,
            pdfborder={0 0 0},
            breaklinks=true}
\urlstyle{same}  % don't use monospace font for urls
\usepackage{graphicx,grffile}
\makeatletter
\def\maxwidth{\ifdim\Gin@nat@width>\linewidth\linewidth\else\Gin@nat@width\fi}
\def\maxheight{\ifdim\Gin@nat@height>\textheight\textheight\else\Gin@nat@height\fi}
\makeatother
% Scale images if necessary, so that they will not overflow the page
% margins by default, and it is still possible to overwrite the defaults
% using explicit options in \includegraphics[width, height, ...]{}
\setkeys{Gin}{width=\maxwidth,height=\maxheight,keepaspectratio}
\IfFileExists{parskip.sty}{%
\usepackage{parskip}
}{% else
\setlength{\parindent}{0pt}
\setlength{\parskip}{6pt plus 2pt minus 1pt}
}
\setlength{\emergencystretch}{3em}  % prevent overfull lines
\providecommand{\tightlist}{%
  \setlength{\itemsep}{0pt}\setlength{\parskip}{0pt}}
\setcounter{secnumdepth}{0}
% Redefines (sub)paragraphs to behave more like sections
\ifx\paragraph\undefined\else
\let\oldparagraph\paragraph
\renewcommand{\paragraph}[1]{\oldparagraph{#1}\mbox{}}
\fi
\ifx\subparagraph\undefined\else
\let\oldsubparagraph\subparagraph
\renewcommand{\subparagraph}[1]{\oldsubparagraph{#1}\mbox{}}
\fi

%%% Use protect on footnotes to avoid problems with footnotes in titles
\let\rmarkdownfootnote\footnote%
\def\footnote{\protect\rmarkdownfootnote}

%%% Change title format to be more compact
\usepackage{titling}

% Create subtitle command for use in maketitle
\newcommand{\subtitle}[1]{
  \posttitle{
    \begin{center}\large#1\end{center}
    }
}

\setlength{\droptitle}{-2em}

  \title{}
    \pretitle{\vspace{\droptitle}}
  \posttitle{}
    \author{}
    \preauthor{}\postauthor{}
    \date{}
    \predate{}\postdate{}
  

\begin{document}

\section{Red Wine Quality Exploration by Hani
Jubail}\label{red-wine-quality-exploration-by-hani-jubail}

\begin{verbatim}
## [1] "C:/Users/PC/Desktop/R"
\end{verbatim}

\begin{quote}
\textbf{introduction}: The dataset were created, using red wine samples.
The inputs include objective tests (e.g.~PH values) and the output is
based on sensory data (median of at least 3 evaluations made by wine
experts). Each expert graded the wine quality between 0 (very bad) and
10 (very excellent).
\end{quote}

\section{Univariate Plots Section}\label{univariate-plots-section}

\begin{verbatim}
##   X fixed.acidity volatile.acidity citric.acid residual.sugar chlorides
## 1 1           7.4             0.70        0.00            1.9     0.076
## 2 2           7.8             0.88        0.00            2.6     0.098
## 3 3           7.8             0.76        0.04            2.3     0.092
## 4 4          11.2             0.28        0.56            1.9     0.075
## 5 5           7.4             0.70        0.00            1.9     0.076
## 6 6           7.4             0.66        0.00            1.8     0.075
##   free.sulfur.dioxide total.sulfur.dioxide density   pH sulphates alcohol
## 1                  11                   34  0.9978 3.51      0.56     9.4
## 2                  25                   67  0.9968 3.20      0.68     9.8
## 3                  15                   54  0.9970 3.26      0.65     9.8
## 4                  17                   60  0.9980 3.16      0.58     9.8
## 5                  11                   34  0.9978 3.51      0.56     9.4
## 6                  13                   40  0.9978 3.51      0.56     9.4
##   quality
## 1       5
## 2       5
## 3       5
## 4       6
## 5       5
## 6       5
\end{verbatim}

\begin{quote}
The quality must be converted into factors because it is a categorical
variable .
\end{quote}

\begin{verbatim}
##   X fixed.acidity volatile.acidity citric.acid residual.sugar chlorides
## 1 1           7.4             0.70        0.00            1.9     0.076
## 2 2           7.8             0.88        0.00            2.6     0.098
## 3 3           7.8             0.76        0.04            2.3     0.092
## 4 4          11.2             0.28        0.56            1.9     0.075
## 5 5           7.4             0.70        0.00            1.9     0.076
## 6 6           7.4             0.66        0.00            1.8     0.075
##   free.sulfur.dioxide total.sulfur.dioxide density   pH sulphates alcohol
## 1                  11                   34  0.9978 3.51      0.56     9.4
## 2                  25                   67  0.9968 3.20      0.68     9.8
## 3                  15                   54  0.9970 3.26      0.65     9.8
## 4                  17                   60  0.9980 3.16      0.58     9.8
## 5                  11                   34  0.9978 3.51      0.56     9.4
## 6                  13                   40  0.9978 3.51      0.56     9.4
##   quality
## 1       5
## 2       5
## 3       5
## 4       6
## 5       5
## 6       5
\end{verbatim}

\includegraphics{projecttemplate_files/figure-latex/Univariate_Plots_2-1.pdf}

\begin{quote}
Most of the red wine from the sample are of level 5 and 6 quality, with
fewer samples of lesser-quality and higher levels at 7 or 8.
\end{quote}

\includegraphics{projecttemplate_files/figure-latex/Univariate_Plots_3-1.pdf}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    8.40    9.50   10.20   10.42   11.10   14.90
\end{verbatim}

\begin{quote}
The mean alcohol content of the wine is at 10\% and it's right-skewed
distribution.
\end{quote}

\includegraphics{projecttemplate_files/figure-latex/Univariate_Plots_5-1.pdf}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   2.740   3.210   3.310   3.311   3.400   4.010
\end{verbatim}

\begin{quote}
on a scale from 0 (very acidic) to 14 (very basic); most wines are
between 3-4 on the pH scale.
\end{quote}

\includegraphics{projecttemplate_files/figure-latex/Univariate_Plots_7-1.pdf}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.9901  0.9956  0.9968  0.9967  0.9978  1.0037
\end{verbatim}

\begin{quote}
the density of water is close to that of water depending on the percent
alcohol and sugar content and we can see from the plot and the mean is
0.9967 .
\end{quote}

\includegraphics{projecttemplate_files/figure-latex/Univariate_Plots_9-1.pdf}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.3300  0.5500  0.6200  0.6581  0.7300  2.0000
\end{verbatim}

\begin{quote}
Sulphates values above 1.5 are outliers.
\end{quote}

\includegraphics{projecttemplate_files/figure-latex/Univariate_Plots_11-1.pdf}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
## 0.01200 0.07000 0.07900 0.08747 0.09000 0.61100
\end{verbatim}

\begin{quote}
chlorides is the amount of salt in the wine and chlorides more than 0.6
are outliers.
\end{quote}

\includegraphics{projecttemplate_files/figure-latex/Univariate_Plots_13-1.pdf}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##   0.900   1.900   2.200   2.539   2.600  15.500
\end{verbatim}

\begin{quote}
the amount of sugar remaining after fermentation stops is around 2
grams/ 1 litre.
\end{quote}

\includegraphics{projecttemplate_files/figure-latex/Univariate_Plots_15-1.pdf}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##    4.60    7.10    7.90    8.32    9.20   15.90
\end{verbatim}

\includegraphics{projecttemplate_files/figure-latex/Univariate_Plots_17-1.pdf}

\begin{verbatim}
##    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
##  0.1200  0.3900  0.5200  0.5278  0.6400  1.5800
\end{verbatim}

\section{Univariate Analysis}\label{univariate-analysis}

\subsubsection{What is the structure of your
dataset?}\label{what-is-the-structure-of-your-dataset}

Number of Instances:1599,Number of Attributes: 12.

1 - fixed acidity: most acids involved with wine or fixed or nonvolatile
(do not evaporate readily).

2 - volatile acidity: the amount of acetic acid in wine, which at too
high of levels can lead to an unpleasant, vinegar taste.

3 - citric acid: found in small quantities, citric acid can add
`freshness' and flavor to wines.

4 - residual sugar: the amount of sugar remaining after fermentation
stops, it's rare to find wines with less than 1 gram/liter and wines
with greater than 45 grams/liter are considered sweet.

5 - chlorides: the amount of salt in the wine.

6 - free sulfur dioxide: the free form of SO2 exists in equilibrium
between molecular SO2 (as a dissolved gas) and bisulfite ion; it
prevents microbial growth and the oxidation of wine.

7 - total sulfur dioxide: amount of free and bound forms of S02; in low
concentrations, SO2 is mostly undetectable in wine, but at free SO2
concentrations over 50 ppm, SO2 becomes evident in the nose and taste of
wine.

8 - density: the density of water is close to that of water depending on
the percent alcohol and sugar content.

9 - pH: describes how acidic or basic a wine is on a scale from 0 (very
acidic) to 14 (very basic); most wines are between 3-4 on the pH scale.

10 - sulphates: a wine additive which can contribute to sulfur dioxide
gas (S02) levels, wich acts as an antimicrobial and antioxidant.

11 - alcohol: the percent alcohol content of the wine.

12 - quality (score between 0 and 10).

\#\url{https://s3.amazonaws.com/udacity-hosted-downloads/ud651/wineQualityInfo.txt}

\subsubsection{What is/are the main feature(s) of interest in your
dataset?}\label{what-isare-the-main-features-of-interest-in-your-dataset}

The main features in the data set are quality , alcohol and residual
sugar. I'd like to determine which features are best for predicting the
the quality of the wine.

\subsubsection{\texorpdfstring{What other features in the dataset do you
think will help support your\\
density, pH, aciditi``fixed or volatile''and chlorides can increase or
decrease the quality of the wine
.}{What other features in the dataset do you think will help support your density, pH, aciditifixed or volatileand chlorides can increase or decrease the quality of the wine .}}\label{what-other-features-in-the-dataset-do-you-think-will-help-support-your-density-ph-aciditifixed-or-volatileand-chlorides-can-increase-or-decrease-the-quality-of-the-wine-.}

\subsubsection{\texorpdfstring{Did you create any new variables from
existing variables in the dataset?\\
not yet but i might group some variables in the Bivariate
section.}{Did you create any new variables from existing variables in the dataset? not yet but i might group some variables in the Bivariate section.}}\label{did-you-create-any-new-variables-from-existing-variables-in-the-dataset-not-yet-but-i-might-group-some-variables-in-the-bivariate-section.}

\subsubsection{\texorpdfstring{Of the features you investigated, were
there any unusual distributions?\\
there is no unusal disributions, most of them are normal or right-skewed
distributions with some
outliers.}{Of the features you investigated, were there any unusual distributions? there is no unusal disributions, most of them are normal or right-skewed distributions with some outliers.}}\label{of-the-features-you-investigated-were-there-any-unusual-distributions-there-is-no-unusal-disributions-most-of-them-are-normal-or-right-skewed-distributions-with-some-outliers.}

\section{Bivariate Plots Section}\label{bivariate-plots-section}

\includegraphics{projecttemplate_files/figure-latex/Bivariate_Plots_2-1.pdf}

\begin{quote}
From the scatter plot above we can see that low quality wine have a less
percentage of alcohol in it, and as the quality increases we can see a
small correlation between alcohol and the overall quality of the wine,
however the highest quality of the wine doesn't have the highest
percentage of alcohol .
\end{quote}

\includegraphics{projecttemplate_files/figure-latex/Bivariate_Plots_2.1-1.pdf}

\begin{quote}
by the mean alcohol values we can see a clearer picture of the alcohol
vs quality and we can say that there is a correlation except for the
level 5 quality .
\end{quote}

\includegraphics{projecttemplate_files/figure-latex/Bivariate_Plots_3-1.pdf}

\includegraphics{projecttemplate_files/figure-latex/Bivariate_Plots_3.1-1.pdf}

\begin{quote}
with the mean pH we can see a negative relationship between pH and the
quality of the wine except the level 5 quality like the alcohol too.
\end{quote}

\includegraphics{projecttemplate_files/figure-latex/Bivariate_Plots_4-1.pdf}

\begin{quote}
the scatter plot above indecates that high quality wine have less
density than low quaity or the average quality wine , however we might
take a deeper look on other factors that might effect the quality beside
the density .
\end{quote}

\includegraphics{projecttemplate_files/figure-latex/Bivariate_Plots_5-1.pdf}

\begin{quote}
both lowest and highest wine quality have alomost the same residual
sugar values , with the some outliers in the middle .
\end{quote}

\includegraphics{projecttemplate_files/figure-latex/Bivariate_Plots_6-1.pdf}

\begin{verbatim}
## 
##  Pearson's product-moment correlation
## 
## data:  df$density and df$fixed.acidity
## t = 35.877, df = 1597, p-value < 2.2e-16
## alternative hypothesis: true correlation is not equal to 0
## 95 percent confidence interval:
##  0.6399847 0.6943302
## sample estimates:
##       cor 
## 0.6680473
\end{verbatim}

\begin{quote}
there is a moderate positive relationship between density and fixed
acidlity .
\end{quote}

\includegraphics{projecttemplate_files/figure-latex/Bivariate_Plots_7-1.pdf}

\begin{quote}
no strong relationship between fixed acidlity and volatile acidlity .
\end{quote}

\includegraphics{projecttemplate_files/figure-latex/Bivariate_Plots_8-1.pdf}

\begin{quote}
there is a very small or even insignificant correlation between the
residual sugar and density.
\end{quote}

\includegraphics{projecttemplate_files/figure-latex/Bivariate_Plots_9-1.pdf}

\begin{quote}
Comparing pH to density, Most wine samples have a pH between 3.0 to 3.5
, and it doesn't have any effect on the density .
\end{quote}

\section{Bivariate Analysis}\label{bivariate-analysis}

\subsubsection{\texorpdfstring{Talk about some of the relationships you
observed in this part of the\\
investigation. How did the feature(s) of interest vary with other
features in\\
the
dataset?}{Talk about some of the relationships you observed in this part of the investigation. How did the feature(s) of interest vary with other features in the dataset?}}\label{talk-about-some-of-the-relationships-you-observed-in-this-part-of-the-investigation.-how-did-the-features-of-interest-vary-with-other-features-in-the-dataset}

\begin{quote}
Quality compared to alcohol percentage, low quality wine have a less\\
percentage of alcohol in it, and as the quality increases we can see a
small\\
correlation between alcohol and the overall quality of the wine,
however\\
the highest quality of the wine doesn't have the highest\\
percentage of alcohol .
\end{quote}

\begin{quote}
With The mean pH we can see a negative relationship between pH and\\
the quality of the wine.
\end{quote}

\begin{quote}
The high quality wine have less density than low quaity or the average
quality wine.
\end{quote}

\begin{quote}
conmparing quality to residual sugar, both lowest and highest\\
wine quality have alomost the same residual sugar values , with the\\
some outliers in the middle .
\end{quote}

\subsubsection{\texorpdfstring{Did you observe any interesting
relationships between the other features\\
}{Did you observe any interesting relationships between the other features }}\label{did-you-observe-any-interesting-relationships-between-the-other-features}

\begin{quote}
There is a moderate positive relationship between density and fixed
acidlity .
\end{quote}

\begin{quote}
No strong relationship between fixed acidlity and volatile acidlity .
\end{quote}

\begin{quote}
There is a very small or even insignificant correlation between the
residual sugar and density.
\end{quote}

\subsubsection{What was the strongest relationship you
found?}\label{what-was-the-strongest-relationship-you-found}

\begin{quote}
The positive relationship between density and fixed acidlity .
\end{quote}

\section{Multivariate Plots Section}\label{multivariate-plots-section}

\includegraphics{projecttemplate_files/figure-latex/Multivariate_Plots-1.pdf}

\includegraphics{projecttemplate_files/figure-latex/Multivariate_Plots2-1.pdf}

\includegraphics{projecttemplate_files/figure-latex/Multivariate_Plots3-1.pdf}
\includegraphics{projecttemplate_files/figure-latex/Multivariate_Plots4-1.pdf}

\begin{quote}
When we added the quality to see it against the fixed acidity vs density
, we can not find any corrlation between them and the quality,also
alcohol,pH and residual sugar too.
\end{quote}

\includegraphics{projecttemplate_files/figure-latex/Multivariate_Plots5-1.pdf}

\includegraphics{projecttemplate_files/figure-latex/Multivariate_Plots6-1.pdf}

\includegraphics{projecttemplate_files/figure-latex/Multivariate_Plots7-1.pdf}

\includegraphics{projecttemplate_files/figure-latex/Multivariate_Plots8-1.pdf}

\includegraphics{projecttemplate_files/figure-latex/Multivariate_Plots9-1.pdf}

\begin{quote}
\begin{quote}
the relationship between alcohol percentage and the quality\\
vs (pH,density,residual sugar and both volatile\\
and fixed acidity) shows no correlation between all of them.\\
\end{quote}
\end{quote}

\begin{verbatim}
## 
## Calls:
## m1: lm(formula = as.numeric(quality) ~ alcohol, data = df)
## m2: lm(formula = as.numeric(quality) ~ alcohol + pH, data = df)
## m3: lm(formula = as.numeric(quality) ~ alcohol + pH + density, data = df)
## m4: lm(formula = as.numeric(quality) ~ alcohol + pH + density + residual.sugar, 
##     data = df)
## m5: lm(formula = as.numeric(quality) ~ alcohol + pH + density + residual.sugar + 
##     fixed.acidity, data = df)
## m6: lm(formula = as.numeric(quality) ~ alcohol + pH + volatile.acidity, 
##     data = df)
## 
## ========================================================================================================
##                          m1            m2            m3            m4            m5            m6       
## --------------------------------------------------------------------------------------------------------
##   (Intercept)          -0.125         2.426***    -11.593       -20.481        22.579         2.269***  
##                        (0.175)       (0.387)      (11.293)      (12.444)      (21.430)       (0.369)    
##   alcohol               0.361***      0.386***      0.397***      0.406***      0.361***      0.330***  
##                        (0.017)       (0.017)       (0.019)       (0.020)       (0.027)       (0.017)    
##   pH                                 -0.850***     -0.808***     -0.802***     -0.443*       -0.422***  
##                                      (0.116)       (0.121)       (0.121)       (0.189)       (0.115)    
##   density                                          13.811        22.673       -21.802                   
##                                                   (11.119)      (12.280)      (21.807)                  
##   residual.sugar                                                 -0.023        -0.006                   
##                                                                  (0.014)       (0.015)                  
##   fixed.acidity                                                                 0.061*                  
##                                                                                (0.025)                  
##   volatile.acidity                                                                           -1.279***  
##                                                                                              (0.099)    
## --------------------------------------------------------------------------------------------------------
##   R-squared             0.227         0.252         0.253         0.254         0.257         0.323     
##   adj. R-squared        0.226         0.251         0.251         0.252         0.255         0.321     
##   sigma                 0.710         0.699         0.699         0.698         0.697         0.665     
##   F                   468.267       268.888       179.834       135.753       110.165       253.328     
##   p                     0.000         0.000         0.000         0.000         0.000         0.000     
##   Log-likelihood    -1721.057     -1694.466     -1693.693     -1692.252     -1689.205     -1615.101     
##   Deviance            805.870       779.508       778.755       777.353       774.396       705.845     
##   AIC                3448.114      3396.931      3397.385      3396.504      3392.411      3240.202     
##   BIC                3464.245      3418.440      3424.271      3428.767      3430.051      3267.087     
##   N                  1599          1599          1599          1599          1599          1599         
## ========================================================================================================
\end{verbatim}

\begin{quote}
this linear model can only explain 32\% of the quality from the samples
in ~ the red wine dataset with R-squared = 0.323 adding the most
features\\
that we are interested in (alcohol,pH,density,residual sugar,
fixed.acidity and vovolatileacidity) .
\end{quote}

\section{Multivariate Analysis}\label{multivariate-analysis}

\subsubsection{\texorpdfstring{Talk about some of the relationships you
observed in this part of the\\
investigation. Were there features that strengthened each other in terms
of\\
looking at your feature(s) of
interest?}{Talk about some of the relationships you observed in this part of the investigation. Were there features that strengthened each other in terms of looking at your feature(s) of interest?}}\label{talk-about-some-of-the-relationships-you-observed-in-this-part-of-the-investigation.-were-there-features-that-strengthened-each-other-in-terms-of-looking-at-your-features-of-interest}

\begin{quote}
there was no features that significantly strength each other in the\\
Multivariate Analysis.
\end{quote}

\begin{quote}
the relationship between alcohol percentage and the quality\\
vs (pH,density,residual sugar and both volatile\\
and fixed acidity) shows no correlation between all of them.\\
\end{quote}

\begin{quote}
When we added the quality to see it against the fixed acidity vs density
,\\
we can not find any corrlation between them and the quality,also
alcohol,pH\\
and residual sugar too.
\end{quote}

\subsubsection{Were there any interesting or surprising interactions
between
features?}\label{were-there-any-interesting-or-surprising-interactions-between-features}

\begin{quote}
The Multivariate Analysis we didn't find any surprising interactions
between\\
the main features.
\end{quote}

\subsubsection{\texorpdfstring{OPTIONAL: Did you create any models with
your dataset? Discuss the\\
strengths and limitations of your
model.}{OPTIONAL: Did you create any models with your dataset? Discuss the strengths and limitations of your model.}}\label{optional-did-you-create-any-models-with-your-dataset-discuss-the-strengths-and-limitations-of-your-model.}

\begin{quote}
I have created a linear model to predict the quality of the wine with\\
the other features in the data set, and by looking at the results we
can\\
tell that it only predicts 32\% of the quality which is not that
significant.
\end{quote}

\section{Final Plots and Summary}\label{final-plots-and-summary}

\subsubsection{Plot One}\label{plot-one}

\includegraphics{projecttemplate_files/figure-latex/unnamed-chunk-1-1.pdf}

\subsubsection{Description One}\label{description-one}

\begin{quote}
\begin{quote}
The Box plot of\\
``Alcohol Percentage by quality'' indicates that there is a correlation
between Alcohol\\
Percentage and quality and the reason that I decided to\\
create a box plot instead of the scatter plot in the univariate\\
section is the box plot shows the mean and the range for each\\
quality group and it makes it easier to understand the relationship\\
between the variables.
\end{quote}
\end{quote}

\subsubsection{Plot Two}\label{plot-two}

\includegraphics{projecttemplate_files/figure-latex/Plot_Two-1.pdf}

\subsubsection{Description Two}\label{description-two}

\begin{quote}
this scatter plot shows the correlation between Fixed Acidity and\\
the Denisty, and there is a modrete positive relationship between
them,\\
however when we add the quality to the plot we can see that quality 5
and 6\\
are the most common .
\end{quote}

\subsubsection{Plot Three}\label{plot-three}

\includegraphics{projecttemplate_files/figure-latex/Plot_Three-1.pdf}

\subsubsection{Description Three}\label{description-three}

\begin{quote}
This jitter plot is a clearer version of the scatter plot for the pH\\
and quality and the added layer of box plots shows the mean and the
range\\
for the pH for each quality, and we can see a correlation and a
negative\\
relationship between the pH and the quality.
\end{quote}

\section{Reflection}\label{reflection}

\begin{quote}
The red wine dataset contains information about 1599 samples and 12
variables. First i examined each individual variable from the dataset to
understand the data\\
and started asking some questions and there were some trends in the data
. The most important feature of the data is quality of the wine however
the vast majority\\
of the samples were at level 5 and 6 , so there was a low amount of al
lesser or higher\\
quality. i tested lot of combination the bivariant section and i didn't
find a single feature that strongly contributed to the\\
quality of the wine except the alcohol we some correlation and the pH we
a very small\\
correlation. In the multivariant section i took a deeper look into how
features interact with each other and the main\\
focus was the quality m but i couldn't find a significant relationship.
i built a linear model that contains the most important feature to see
how each one of\\
them will explain the quality and how all of them , the results were not
very\\
informative because it explained only 32\% of the quality when we add
them all together.\\
Limitations include the small number of samples from the high and low
quality\\
wine and also other factors like The aging of wine which is potentially
improved\\
the quality, also the county of origin. All of these missing information
i believe could explain the quality beside\\
the existing variables.
\end{quote}

\subsubsection{Sources}\label{sources}

Aging of wine \url{https://en.wikipedia.org/wiki/Aging_of_wine}. adding
the \% sgin to the plot
\url{https://stackoverflow.com/questions/35967047/appending-symbol-with-y-axis-values-in-ggplot2}.
changing the legend name
\url{https://stackoverflow.com/questions/33398033/change-ggplot-legend-title}.
adjusting to plot title to the cener of the plot
\url{https://stackoverflow.com/questions/40675778/center-plot-title-in-ggplot2}.


\end{document}
